trigger: none

parameters:
  - name: action
    type: string
    default: 'addOrgUser'
    values:
      - addOrgUser
      - removeUser
      - addProjectUser
  - name: userEmail
    type: string
    default: ''
  - name: accountLicenseType
    type: string
    default: 'stakeholder'
  - name: projectName
    type: string
    default: ''
  - name: groupType
    type: string
    default: 'projectReader'

variables:
  ADO_ORG: 'tejaraghumandala0'

pool:
  name: Default

steps:
  - ${{ if eq(parameters.action, 'addOrgUser') }}:
    - template: templates/add-user-org.yml
      parameters:
        userEmail: ${{ parameters.userEmail }}
        accountLicenseType: ${{ parameters.accountLicenseType }}

  - ${{ if eq(parameters.action, 'removeUser') }}:
    - template: templates/remove-user-org.yml
      parameters:
        userEmail: ${{ parameters.userEmail }}

  - ${{ if eq(parameters.action, 'addProjectUser') }}:
    - template: templates/add-user-project.yml
      parameters:
        userEmail: ${{ parameters.userEmail }}
        accountLicenseType: ${{ parameters.accountLicenseType }}
        projectName: ${{ parameters.projectName }}
        groupType: ${{ parameters.groupType }}
